name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test with pytest
      run: |
        poetry run pytest

    - name: Install condax
      run: |
        poetry run condax ensure-path
        mkdir -p "${HOME}/.local/bin"

    - name: Install black via condax
      run: |
        poetry run condax install black

    - name: Run black --help
      run: |
        export PATH="$PATH:${HOME}/.local/bin"
        black --help
      if: matrix.os != 'windows-latest'

    - name: Remove black from condax environments
      run: |
        poetry run condax remove black
